SOURCE_F = 1ntRpretR.cc interpreter.cc parser.cc stack.cc helpers.cc
FLAGS = -o 1ntR -Wall -Wextra

1ntR: 1ntRpretR.cc parser.cc parser.h interpreter.cc interpreter.h commands.h stack.cc stack.h helpers.cc helpers.h
	$(CXX) $(SOURCE_F) $(FLAGS)
